[project]
name = "comfyui-selector"
description = "𝌸 exdysa workflow elements. Selector - Preset aspect ratios & settings. node. Recourse - Node wiring failsafe & logic."
version = "1.3.0"
license = "LICENSE"

[project.urls]
Repository = "https://github.com/exdysa/comfyui-selector"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "exdysa"
DisplayName = "comfyui-selector"
Icon = ""